version: 2.1

orbs:
  node: circleci/node@4.2.1

jobs:
  build_deploy_stg:
    executor:
      name: node/default
      tag: '12.19.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build Stg
          command: yarn build
      - run:
          name: Deploy Stg
          command: ./node_modules/.bin/firebase use monla-project && ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_deploy_stg:
    jobs:
      - build_deploy_stg:
          filters:
            branches:
              only: master
